Controllers/LuasanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using luasan.Models;
using surplus.Models;

namespace surplus.Controllers
{
    public class LuasanController : Controller
    {
        private readonly SurplusContext _context;

        public LuasanController(SurplusContext context)
        {
            _context = context;
        }

        // GET: Luasan
        public async Task<IActionResult> Index()
        {
            return View(await _context.masterluasan.ToListAsync());
        }

        // GET: Luasan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var luasan = await _context.masterluasan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (luasan == null)
            {
                return NotFound();
            }

            return View(luasan);
        }

        // GET: Luasan/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Luasan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Lokasi,Kapasitas")] Luasan luasan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(luasan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(luasan);
        }

        // GET: Luasan/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var luasan = await _context.masterluasan.FindAsync(id);
            if (luasan == null)
            {
                return NotFound();
            }
            return View(luasan);
        }

        // POST: Luasan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Lokasi,Kapasitas")] Luasan luasan)
        {
            if (id != luasan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(luasan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LuasanExists(luasan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(luasan);
        }

        // GET: Luasan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var luasan = await _context.masterluasan
                .FirstOrDefaultAsync(m => m.Id == id);
            if (luasan == null)
            {
                return NotFound();
            }

            return View(luasan);
        }

        // POST: Luasan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var luasan = await _context.masterluasan.FindAsync(id);
            _context.masterluasan.Remove(luasan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LuasanExists(int id)
        {
            return _context.masterluasan.Any(e => e.Id == id);
        }
    }
}

Controllers/MaterialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using material.Models;
using surplus.Models;

namespace surplus.Controllers
{
    public class MaterialController : Controller
    {
        private readonly SurplusContext _context;

        public MaterialController(SurplusContext context)
        {
            _context = context;
        }

        // GET: Material
        public async Task<IActionResult> Index()
        {
            return View(await _context.mastermaterial.ToListAsync());
        }

        // GET: Material/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.mastermaterial
                .FirstOrDefaultAsync(m => m.Id == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // GET: Material/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Material/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nama_material")] Material material)
        {
            if (ModelState.IsValid)
            {
                _context.Add(material);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        // GET: Material/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.mastermaterial.FindAsync(id);
            if (material == null)
            {
                return NotFound();
            }
            return View(material);
        }

        // POST: Material/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nama_material")] Material material)
        {
            if (id != material.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(material);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaterialExists(material.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(material);
        }

        // GET: Material/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var material = await _context.mastermaterial
                .FirstOrDefaultAsync(m => m.Id == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // POST: Material/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var material = await _context.mastermaterial.FindAsync(id);
            _context.mastermaterial.Remove(material);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialExists(int id)
        {
            return _context.mastermaterial.Any(e => e.Id == id);
        }
    }
}

Controllers/TipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using surplus.Models;
using tipe.Models;

namespace surplus.Controllers
{
    public class TipeController : Controller
    {
        private readonly SurplusContext _context;

        public TipeController(SurplusContext context)
        {
            _context = context;
        }

        // GET: Tipe
        public async Task<IActionResult> Index()
        {
            return View(await _context.mastertipe.ToListAsync());
        }

        // GET: Tipe/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipe = await _context.mastertipe
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipe == null)
            {
                return NotFound();
            }

            return View(tipe);
        }

        // GET: Tipe/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tipe/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Kode_tipe,Nama_tipe")] Tipe tipe)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipe);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipe);
        }

        // GET: Tipe/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipe = await _context.mastertipe.FindAsync(id);
            if (tipe == null)
            {
                return NotFound();
            }
            return View(tipe);
        }

        // POST: Tipe/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Kode_tipe,Nama_tipe")] Tipe tipe)
        {
            if (id != tipe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipe);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipeExists(tipe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipe);
        }

        // GET: Tipe/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipe = await _context.mastertipe
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipe == null)
            {
                return NotFound();
            }

            return View(tipe);
        }

        // POST: Tipe/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipe = await _context.mastertipe.FindAsync(id);
            _context.mastertipe.Remove(tipe);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipeExists(int id)
        {
            return _context.mastertipe.Any(e => e.Id == id);
        }
    }
}

Controllers/UomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using surplus.Models;
using uom.Models;

namespace surplus.Controllers
{
    public class UomController : Controller
    {
        private readonly SurplusContext _context;

        public UomController(SurplusContext context)
        {
            _context = context;
        }

        // GET: Uom
        public async Task<IActionResult> Index()
        {
            return View(await _context.masteruom.ToListAsync());
        }

        // GET: Uom/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uom = await _context.masteruom
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uom == null)
            {
                return NotFound();
            }

            return View(uom);
        }

        // GET: Uom/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Uom/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nama_uom")] Uom uom)
        {
            if (ModelState.IsValid)
            {
                _context.Add(uom);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(uom);
        }

        // GET: Uom/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uom = await _context.masteruom.FindAsync(id);
            if (uom == null)
            {
                return NotFound();
            }
            return View(uom);
        }

        // POST: Uom/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nama_uom")] Uom uom)
        {
            if (id != uom.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(uom);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UomExists(uom.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(uom);
        }

        // GET: Uom/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var uom = await _context.masteruom
                .FirstOrDefaultAsync(m => m.Id == id);
            if (uom == null)
            {
                return NotFound();
            }

            return View(uom);
        }

        // POST: Uom/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var uom = await _context.masteruom.FindAsync(id);
            _context.masteruom.Remove(uom);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UomExists(int id)
        {
            return _context.masteruom.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Source Material- surplus</title>
   
    <link href="~/lib/datatables/css/dataTables.bootstrap.css" rel="stylesheet">
    <link href="~/lib/bootstrap_bakk/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
      .dataTables_filter { margin-left:520px }
      .dataTables_length{ margin-left: -16em }
      div.dataTables_paginate { margin-right: -67em; }
      .modal {
            text-align: center;
            }


            .modal-dialog {
            display: inline-block;
            text-align: left;
            vertical-align: middle;
            }
    
    </style>

    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img alt="CoreProgram" data-height="50" data-width="100" id="main-logo" src="~/css/logo.png"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between kanan">
                    <ul class="navbar-nav flex-grow-1 logonya">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"> <i class="glyphicon glyphicon-home"></i> Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materialsurplus" asp-action=""> <i class="glyphicon glyphicon-th-list"></i> Material Surplus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pengambilan" asp-action=""> <i class="glyphicon glyphicon-th-list"></i> Pengambilan Material</a>
                        </li>
                       
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <i class="glyphicon glyphicon-folder-open"></i>  Master Data
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-area="" asp-controller="Material" asp-action="">Master Source Material</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Tipe" asp-action="">Master Tipe</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Subtipe" asp-action="">Master Subtipe</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Uom" asp-action="">Master Uom</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Luasan" asp-action="">Master Luasan</a>
                                                                
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted noPrint">
        <div class="container">
            &copy; 2021 - surplus - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap_bakk/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-2.1.4.min.js'"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script>

            $(document).ready(function() {
                $('#table').DataTable(
                    
                    {     

                "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
                    "iDisplayLength": 5
                } 
                    );
            } );


            function checkAll(bx) {
            var cbs = document.getElementsByTagName('input');
            for(var i=0; i < cbs.length; i++) {
                if(cbs[i].type == 'checkbox') {
                cbs[i].checked = bx.checked;
                }
            }
            } 
    </script>

  
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>